name: Java CI

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  release:
    types:
     - created

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 12, 13, 14, 15]
    name: Java ${{ matrix.java }} Run
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven Dependencies
      uses: actions/cache@v2.1.3
      with:
        path: ~/.m2/repository
        key: ajts-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ajts-maven-
    - name: Test with Maven and JDK ${{ matrix.java }}
      run: mvn -B clean test
  sonar-scanner:
    needs: test
    runs-on: ubuntu-latest
    name: SonarCloud Java 14
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Cache Maven Dependencies
      uses: actions/cache@v2.1.3
      with:
        path: ~/.m2/repository
        key: ajts-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ajts-maven-
    - name: Run SonarScanner for SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B -P coverage clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=artemis-java-test-sandbox -Dsonar.organization=maisikoleni -Dsonar.host.url=https://sonarcloud.io
  deploy:
    if: startsWith(github.event.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven Dependencies
      uses: actions/cache@v2.1.3
      with:
        path: ~/.m2/repository
        key: ajts-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ajts-maven-
    - name: Build and Deploy with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>MaisiKoleni</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        mvn -B -Dmaven.wagon.http.pool=false clean deploy -P github
